# Generated by Django 4.1.3 on 2022-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
