# Generated by Django 4.1.3 on 2022-11-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='S_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
